--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/antbag-dev/VoteStreak
build-by-default: true
branches:
- main
projects:
  VoteStreak:
    icon: "signaling.gif"
    path: ""
    lint:
      phpstan: false
    libs:
      FormAPI:
        src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
      Commando:
        src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.1
...
